sudo: required
services:
  - docker
language: java
#language: r
#r:
#  - release
install: true
jdk: oraclejdk8
branches:
  only:
    - master
before_install:
#  - sudo docker rmi -f srp33/${imageName}:${version}
  - sudo docker build -t srp33/shinylearner:alpha1 Dockerfile
#script:
#- cd Validation; ./generate_data; cd ..
#- sh TestScripts/classification_montecarlo
