###################################################
###################################################
# Make sure to only modify the template file!!!!!!!
###################################################
###################################################

sudo: required
services:
  - docker
language: java
install: true
jdk: oraclejdk8
branches:
  only:
    - master
notifications:
  email: true
script:
  - scripts/build
  - cat "testing" > testing
#  - tar -zcf ShinyLearner.tar.gz shinylearner.jar scripts AlgorithmScripts README.md VERSION BuildTests BuildTestExpectedOutput LICENSE UserScripts lib
#  - sudo docker build -t srp33/shinylearner:version191 .
#  - mkdir input output
#  - cp Validation/*.tsv.gz input/
#  - sudo docker run --rm --name inputdata -v $(pwd)/input:/input -v $(pwd)/output:/output srp33/shinylearner:version191 /BuildTests/all
#  - set -o errexit
#  - python BuildTests/CheckLogFiles.py "output/overall.log" 1
#  - echo "All tests passed!!!"
#  - git tag $(cat VERSION)
#  - git push origin $(cat VERSION)
#  - sudo docker run --rm --name inputdata -v $(pwd)/input:/input -v $(pwd)/output:/output srp33/shinylearner:version191 rm -rf /BuildTest*
#  - sudo docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
#  - sudo docker push srp33/shinylearner:version191
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: testing
  skip_cleanup: true
  on:
    tags: true
