###################################################
###################################################
# Make sure to only modify the template file!!!!!!!
###################################################
###################################################

sudo: required
services:
  - docker
language: java
install: true
jdk: oraclejdk8
branches:
  only:
    - master
script:
  - scripts/build
  - tar -zcvf ShinyLearner.tar.gz shinylearner.jar scripts AlgorithmScripts README.md VERSION Validation TestScripts build.xml LICENSE UserScripts
  - sudo docker build -t srp33/shinylearner:version4 .


#- cd Validation; ./generate_data; cd ..
#- sh TestScripts/classification_montecarlo
#
#  - sudo docker pull srp33/shinylearner_environment:version1
#  - sudo docker rmi -f srp33/shinylearner:version4
