###################################################
###################################################
# Make sure to only modify the template file!!!!!!!
###################################################
###################################################

sudo: required
services:
  - docker
language: java
install: true
jdk: oraclejdk8
branches:
  only:
    - master
script:
  - scripts/build
  - tar -zcvf ShinyLearner.tar.gz shinylearner.jar scripts AlgorithmScripts README.md VERSION BuildTests LICENSE UserScripts
  - sudo docker build -t srp33/shinylearner:version57 .
  - mkdir input output
  - cp Validation/*.tsv.gz input/
  - sudo docker run --rm --name inputdata -v $(pwd)/input:/input -v $(pwd)/output:/output srp33/shinylearner:version57 /BuildTests/all | tee output/log
  - grep "[FAILED]" output/log

#  - sudo docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
#  - sudo docker push srp33/shinylearner:version57
#
#  - sudo docker pull srp33/shinylearner_environment:version1
#  - sudo docker rmi -f srp33/shinylearner:version57
