###################################################
###################################################
# Make sure to only modify the template file!!!!!!!
###################################################
###################################################

sudo: required
services:
  - docker
language: java
install: true
jdk: oraclejdk8
branches:
  only:
    - master
script:
  - set -o errexit
  - BuildTests/all
  - echo "$DOCKER_PASS" | sudo docker login -u="$DOCKER_USER" --password-stdin
  - sudo docker push srp33/shinylearner:version451
