language: java
language: r
r:
  - release
install: true
jdk: oraclejdk8
branches:
  only:
    - master
script:
- cd Validation; ./generate_data; cd ..
- sh TestScripts/classification_montecarlo
notifications:
  email:
    - goldfish1434@yahoo.com
