###################################################
###################################################
# Make sure to only modify the template file!!!!!!!
###################################################
###################################################

sudo: required
services:
  - docker
language: java
install: true
jdk: oraclejdk8
branches:
  only:
    - master
script:
  - scripts/build
  - tar -zcf ShinyLearner.tar.gz shinylearner.jar scripts AlgorithmScripts README.md VERSION BuildTests BuildTestExpectedOutput LICENSE UserScripts
  - sudo docker build -t srp33/shinylearner:version251 .
  - mkdir input output
  - cp Validation/*.gz input/
  - sudo docker run --rm --name inputdata -v $(pwd)/input:/input -v $(pwd)/output:/output srp33/shinylearner:version251 /BuildTests/all
  - set -o errexit
  - python BuildTests/CheckLogFiles.py "output/log.overall" 1
  - echo "All tests passed!!!"
  - sudo docker run --rm --name inputdata -v $(pwd)/input:/input -v $(pwd)/output:/output srp33/shinylearner:version251 rm -rf /BuildTest*
  - sudo docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - sudo docker push srp33/shinylearner:version251
